// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQyy_FXhX4mH2lpfdV9yIFh6NVF9j9LkM',
    appId: '1:464418599165:web:1cb668156dd89d0f6b4e94',
    messagingSenderId: '464418599165',
    projectId: 'fasum-app-dec51',
    authDomain: 'fasum-app-dec51.firebaseapp.com',
    databaseURL: 'https://fasum-app-dec51-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-app-dec51.firebasestorage.app',
    measurementId: 'G-9XPKTKQ3N5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg7QqbHHNnhGlHi1sotIj4GV6626MlcfE',
    appId: '1:464418599165:android:bb9732a8b0799d956b4e94',
    messagingSenderId: '464418599165',
    projectId: 'fasum-app-dec51',
    databaseURL: 'https://fasum-app-dec51-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-app-dec51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2Z6CU9-0d1ldiS2gai0gosqFOE6dzQb0',
    appId: '1:464418599165:ios:5a4e0ecd1473cd226b4e94',
    messagingSenderId: '464418599165',
    projectId: 'fasum-app-dec51',
    databaseURL: 'https://fasum-app-dec51-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-app-dec51.firebasestorage.app',
    iosBundleId: 'com.example.umkmproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2Z6CU9-0d1ldiS2gai0gosqFOE6dzQb0',
    appId: '1:464418599165:ios:5a4e0ecd1473cd226b4e94',
    messagingSenderId: '464418599165',
    projectId: 'fasum-app-dec51',
    databaseURL: 'https://fasum-app-dec51-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-app-dec51.firebasestorage.app',
    iosBundleId: 'com.example.umkmproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQyy_FXhX4mH2lpfdV9yIFh6NVF9j9LkM',
    appId: '1:464418599165:web:36a0f268569b088a6b4e94',
    messagingSenderId: '464418599165',
    projectId: 'fasum-app-dec51',
    authDomain: 'fasum-app-dec51.firebaseapp.com',
    databaseURL: 'https://fasum-app-dec51-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-app-dec51.firebasestorage.app',
    measurementId: 'G-PHK7D5TFT0',
  );

}